on:
  pull_request:
    branches:
      - main

name: coverage

permissions:
  contents: write
  pull-requests: write

jobs:
  release-reusable:
    uses: anyproto/shared-actions/.github/workflows/coverage-go-daemons-reusable.yml@coverage-go-daemons
    secrets: inherit # pass all secrets
    with:
      start_redis: true
