on:
  pull_request:
    branches:
      - main

name: coverage

permissions:
  contents: write
  pull-requests: write

jobs:
  coverage-reusable:
    uses: anyproto/shared-actions/.github/workflows/coverage-go-daemons-reusable.yml@v1
    secrets: inherit # pass all secrets
    with:
      start_redis: true
