on:
  release:
    types: [published]

name: push-docker-image-release

jobs:
  push-docker-image-release:
    uses: anyproto/any-sync-node/.github/workflows/push-docker-image-reusable.yml@main
    secrets: inherit
    with:
      release: ${{ github.event.release.tag_name }}
      dockerfile-run: apt-get update && apt-get install -y ca-certificates
      dockerfile-cmd: '["/bin/any-sync-filenode", "-c", "/etc/any-sync-filenode/config.yml"]'
